<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jsonnet</string>
	</array>
	<key>name</key>
	<string>Jsonnet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(\d+([Ee][+-]?\d+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+[.]\d*([Ee][+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[.]\d+([Ee][+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](acos|asin|atan|ceil|char|codepoint|cos|exp|exponent)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](filter|floor|force|length|log|makeArray|mantissa)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](objectFields|objectHas|pow|sin|sqrt|tan|type|thisFile)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](acos|asin|atan|ceil|char|codepoint|cos|exp|exponent)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](abs|assertEqual|escapeString(Bash|Dollars|Json|Python))\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](filterMap|flattenArrays|foldl|foldr|format|join)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](lines|manifest(Ini|Python(Vars)?)|map|max|min|mod)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](set|set(Diff|Inter|Member|Union)|sort)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstd[.](range|split|stringChars|substr|toString|uniq)\b</string>
			<key>name</key>
			<string>support.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[$]\b</string>
			<key>name</key>
			<string>variable.language.jsonnet</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.double.jsonnet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\(["\\/bfnrt]|(u[0-9a-fA-F]{4}))</string>
					<key>name</key>
					<string>constant.character.escape.jsonnet</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[^"\\/bfnrtu]</string>
					<key>name</key>
					<string>invalid.illegal.jsonnet</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\|\|\|</string>
			<key>end</key>
			<string>\|\|\|</string>
			<key>name</key>
			<string>string.unquoted.block.jsonnet</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>//.*$</string>
			<key>name</key>
			<string>comment.line.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.block.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[a-zA-Z_][a-z0-9A-Z_]*\s*(\([^)]*\))?\s*+?::?:?</string>
			<key>name</key>
			<string>entity.name.function.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(import|importstr)\b</string>
			<key>name</key>
			<string>storage.type.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function)\b</string>
			<key>name</key>
			<string>keyword.other.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(self|super)\b</string>
			<key>name</key>
			<string>variable.language.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|then|else|for|in)\b</string>
			<key>name</key>
			<string>keyword.control.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(local|tailstrict)\b</string>
			<key>name</key>
			<string>keyword.other.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.jsonnet</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(error|assert)\b</string>
			<key>name</key>
			<string>keyword.control.jsonnet</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.jsonnet</string>
	<key>uuid</key>
	<string>1cdce16b-6ddf-4d5f-8890-a6c6f5fbf625</string>
</dict>
</plist>
